---
title: "Wrack_degradation_code"
author: "Ric DeSantiago"
date: "2023-04-26"
output: html_document
---


#libraries
```{r}
library(knitr)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(ggfortify)
library(lme4)
library(car)
library(nlme)
library(ggpubr)
library(multcompView)
library(boot)
library(Hotelling)
library(mvnTest)
library(vegan)
library(factoextra)
library(FactoMineR)
library(agricolae)
library(glmm)
library(HH)
library(ggpubr)
library(rstatix)
```



#degradation experiment 
```{r}
#load data
degradation<-read.csv("DegradationExperimenttrials2021.csv", header=TRUE)
view(degradation)
na.omit(degradation)

degradation<-subset(degradation, !trt == "Control")
degradation$trial_no.<-as.factor(degradation$trial_no.)

fig<- ggplot(degradation, aes(x=grazer_spp., y= Wd, fill= algae_spp.)) + 
  geom_boxplot() + theme_bw() +  facet_grid(trial_no. ~ ., scales = "free_y", labeller = as_labeller(c("1" = "One Week", "2" = "Two Weeks")))
fig






ontogeny<-read.csv("JuvenileVSAdultSargassumAssay.csv", header=TRUE)
na.omit(ontogeny)
view(ontogeny)
ontogeny<-subset(ontogeny, !trt == "control")

ontogenyfig<- ggplot(ontogeny, aes(x=grazer_spp., y= algae_Wd, fill= algae_spp.)) + 
  geom_boxplot() + theme_bw()  
ontogenyfig








rvf<-read.csv("AgarVSwholeTissueAssasy.csv", header=TRUE)
na.omit(rvf)
view(rvf)
rvf<-subset(rvf, !Treatment == "control")

rvffig<- ggplot(rvf, aes(x=Grazer_Spp., y= Algae_Wd, fill= Algae)) + 
  geom_boxplot() + theme_bw()  
rvffig



```


```{r}
summary(cars)
```

```{r}
plot(pressure)
```

